workflows:
  expo-android-apk:
    name: Expo Android APK (Free Plan)
    max_build_duration: 60

    environment:
      node: 18
      groups:
        - android_signing

    scripts:
      - name: Install dependencies
        script: |
          npm install -g expo-cli
          npm install --legacy-peer-deps

      - name: Expo prebuild (Android)
        script: |
          npx expo prebuild --platform android --no-install

      - name: Build RELEASE APK
        script: |
          cd android
          ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/**/*.apk
